abstract: ~
author: J. Shirley <jshirley@gmail.com>
build_requires: 
  DBD::SQLite: 0
  SQL::Translator: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: DBIx-Class-TimeStamp
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBIx::Class: 0
  DateTime: 0
version: 0.01
